main:
  - name: About
    pageRef: /about/
    weight: 10
  - name: Blog
    pageRef: /blog/
    weight: 20
  - name: Projects
    pageRef: /projects/
    weight: 30
  - name: Sample project
    pageRef: /projects/sample-project/
    parent: Projects
    weight: 1
  - name: Another project
    pageRef: /projects/another-project/
    parent: Projects
    weight: 2
  - name: Tags
    pageRef: /tags/
    weight: 40
social:
  - name: LinkedIn
    pre: fab linkedin
    url: 'https://linkedin.com/'
    weight: 10
  - name: GitHub
    pre: fab fa-github
    url: 'https://github.com/'
    weight: 20
  - name: Medium
    pre: fab medium
    url: 'https://medium.com/'
    weight: 30
sample:
  - name: Blog
    pageRef: /blog/
    weight: 10
  - name: Projects
    pageRef: /projects/
    weight: 20
  - name: Sample project
    pageRef: /projects/sample-project/
    parent: Projects
    weight: 1
  - name: Another project
    pageRef: /projects/another-project/
    parent: Projects
    weight: 2

