main:
  - name: Luana
    pageRef: /about/
    weight: 10
  - name: Blog
    pageRef: /blog/
    weight: 20
  - name: Projetos
    pageRef: /projects/
    weight: 30
  - name: Projeto exemplo
    pageRef: /projects/sample-project/
    parent: Projetos
    weight: 1
  - name: Outro projeto
    pageRef: /projects/another-project/
    parent: Projetos
    weight: 2
  - name: Tags
    pageRef: /tags/
    weight: 40
social:
  - name: Instagram
    pre: fab instagram
    url: 'https://www.instagram.com/luanahoje/'
    weight: 10
